---
exclude_paths:
  - "**/*.md"
  - "**/*.pdf"
  - "**/*.JPG"
  - "**/*.png"
  - "**/*.html"
  - "specs/*"
  - "pipeline/*"
  - "admin/*"
  - ".github/workflows/*"

engines:
  eslint:
    enabled: true
    configFile: pipeline/.eslintrc.yml