name: Codacy Analysis CLI

on:
  push:
    branches: [ "cicd_codequalitytool" ]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@cicd_codequalitytool

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master