name: End-to-End Testing

on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  end-to-end-testing:
    runs-on: ubuntu-latest

    steps:
      
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Prefer the latest

      # Step 3: Install all dependencies (including puppeteer)
      - name: Install puppeteer
        run: npm install puppeteer --save-dev

      # Step 4: Run Puppeteer tests
      - name: Run Puppeteer Tests
        run: |
          for file in test/*.js; do
            echo "Running $file..."
            node "$file"
          done
      
      - name: Check if PNG files exist using glob
        shell: bash
        run: |
          shopt -s nullglob
          png_files=(*.png)
          if [ ${#png_files[@]} -gt 0 ]; then
            echo "There are PNG files found in /test."
            exit 1
          else
            echo "There are no PNG files in /test."
          fi
          
      # Step 5: Post-test cleanup (Optional)
      - name: Cleanup
        if: always()
        run: echo "Clean up completed"
